---
- name: Install Packages
  apt:
    name:
      - gpg
      - sudo
      - ufw
      - vim

- name: enable FireWall
  ufw:
    state: enabled

- name: Allow SSH
  ufw:
    rule: allow
    port: '22'

- name: Allow HTTP
  ufw:
    rule: allow
    port: '80'

- name: Allow HTTPS
  ufw:
    rule: allow
    port: '443'
  
- name: Enable deny Policy
  ufw:
    policy: deny
