---
- name: Add APT key
  apt_key:
    id: "ACCC4CF8"
    url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
    state: present

- name: Add Postgres Sourcelist
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ buster-pgdg main"
    filename: postgresql
    state: present

- name: Install Postgres
  apt:
    update_cache: true
    name:
      - postgresql-common
      - postgresql-12
      - python3-psycopg2
    state: present

- name: "Init user for database's owner"
  become_user: postgres
  become: true
  postgresql_user:
    name: "netbox"
    password: "chohThon9Yoo0ahw"

- name: "Create database"
  become_user: postgres
  become: true
  postgresql_db:
    name: "netbox"
    owner: "netbox"

- name: "Create schema"
  become_user: postgres
  become: true
  postgresql_schema:
    db: "netbox"
    name: "netbox_schema"
    owner: "netbox"

